name: Build and deploy Docker app to Azure
on:
  push:
    branches:
      - master

  # Allow mannually trigger 
  workflow_dispatch: 
  
env:
  APPNAME: AzureWebAppforContainers
  APPLICATIONPATH: Application/aspnet-core-dotnet-core-net6
  #HOSTINGPLAN: AzureWebAppforContainers
  DOCKERFILEPATH: "Application/aspnet-core-dotnet-core-net6"
  REGISTRYSKU: "Standard"
  #REGISTRYNAME: "azurewebappforcontainersacr"
  REGISTRYLOCATION: "East US 2"
  IMAGENAME: "azurewebappforcontainersedd3"
  #RESOURCEGROUPNAME: rg-AzureWebAppforContainers
  #LOCATION: East US 2
  #APPINSIGHTSLOCATION: East US 2
  SUBSCRIPTIONID: f5e66d29-1a7f-4ee3-822e-74f644d3e665
  SKU: S1 Standard
  
  dotnet_version: '6.x.x'
  Azure_Resource_GroupName: 'rg-AzureWebAppforContainerApps'
  Azure_Resource_GroupLocation: 'eastus2'
  CONFIGURATION: Release
  WORKING_DIRECTORY: .
  
jobs:
  build:
    name: Build Application
    runs-on: ubuntu-latest
    steps:

    - name: Checkout
      uses: actions/checkout@v3

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{ env.dotnet_version }}
          
    - name: Azure authentication
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Restore
      run: dotnet restore ./Application/aspnet-core-dotnet-core-net6/aspnet-core-dotnet-core-net6.csproj

    - name: Build
      run: dotnet build ./Application/aspnet-core-dotnet-core-net6/aspnet-core-dotnet-core-net6.csproj --configuration ${{ env.CONFIGURATION }} --no-restore

    - name: Publish
      run: dotnet publish ./Application/aspnet-core-dotnet-core-net6/aspnet-core-dotnet-core-net6.csproj --configuration ${{ env.CONFIGURATION }} --no-build --output './web'

    - name: Upload Build Artifacts-Website
      uses: actions/upload-artifact@v3
      with:
        name: Web
        path: ${{ github.workspace }}/web

    - name: Upload Infrastucture Files
      uses: actions/upload-artifact@v3
      with:
        name: IaC
        path: ${{ github.workspace }}/IaC/*.*

    - name: Upload Docker File
      uses: actions/upload-artifact@v3
      with:
        name: Web
        path: ${{ github.workspace }}/Application/aspnet-core-dotnet-core-net6/Dockerfile

    #- name: Docker Build & Push to ACR
    # run: |
       #docker login ${{ env.REGISTRYNAME }}.azurecr.io --username ${{ steps.acrCredentials.outputs.acr_username }} --password ${{ steps.acrCredentials.outputs.acr_password }}
       #docker build "$GITHUB_WORKSPACE/${{env.DOCKERFILEPATH}}" -f  "${{env.DOCKERFILEPATH}}/Dockerfile" -t ${{ env.REGISTRYNAME }}.azurecr.io/${{ env.IMAGENAME }}:${{ github.sha }}

    # Create Azure container registry
    #- uses: azure/arm-deploy@v1
    #  id: createAcr
    ##  with:
    #    subscriptionId: ${{ env.SUBSCRIPTIONID }}
    #    resourceGroupName: ${{ env.RESOURCEGROUPNAME }}
    #    template: ./ArmTemplates/containerRegistry-template.json
    #    parameters: registryName="${{ env.REGISTRYNAME }}" registryLocation="${{ env.REGISTRYLOCATION }}" registrySku="${{ env.REGISTRYSKU }}"

    #- name: Fetch ACR credentials
    #  id: acrCredentials
    #  continue-on-error: false
    #  run: |
    #      echo "::set-output name=acr_username::`az acr credential show -n ${{ env.REGISTRYNAME }} --query username`"
    #      echo "::set-output name=acr_password::`az acr credential show -n ${{ env.REGISTRYNAME }} --query passwords[0].value`"
    #      echo "::add-mask::`az acr credential show -n ${{ env.REGISTRYNAME }} --query passwords[0].value`"

    #- name: ACR authentication
    #  uses: azure/docker-login@v1
    #  with:
    #    login-server: ${{ env.REGISTRYNAME }}.azurecr.io
    #    username: ${{ steps.acrCredentials.outputs.acr_username }}
    #    password: ${{ steps.acrCredentials.outputs.acr_password }}

    #- name: Docker Build & Push to ACR
    #  run: |
    #    docker login ${{ env.REGISTRYNAME }}.azurecr.io --username ${{ steps.acrCredentials.outputs.acr_username }} --password ${{ steps.acrCredentials.outputs.acr_password }}
    #    docker build "$GITHUB_WORKSPACE/${{env.DOCKERFILEPATH}}" -f  "${{env.DOCKERFILEPATH}}/Dockerfile" -t ${{ env.REGISTRYNAME }}.azurecr.io/${{ env.IMAGENAME }}:${{ github.sha }}
    #    #docker tag ${{ env.IMAGENAME }}:${{ github.sha }} ${{ env.IMAGENAME }}:latest
    #    docker push ${{ env.REGISTRYNAME }}.azurecr.io/${{ env.IMAGENAME }}:${{ github.sha }}

  deploy_infrastructure:
    runs-on: ubuntu-latest
    needs: build
    outputs:
      output_webSiteName: ${{ steps.Infra.outputs.out_webSiteName }}
      output_keyvaultName: ${{ steps.Infra.outputs.out_keyvaultName }}
      output_containerregistryName: ${{ steps.Infra.outputs.out_containerregistryName }}

    name: Deploy Infrastructure
    steps:
    - uses: actions/checkout@master

    - name: Azure authentication
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Ensure Resource Group Exists
      uses: Azure/CLI@v1
      continue-on-error: true
      with:
        inlineScript: |
          #!/bin/bash
          az group create --name ${{ env.Azure_Resource_GroupName }} --location ${{ env.Azure_Resource_GroupLocation }}

    - name: Ensure Resource Group is UnLocked
      uses: Azure/CLI@v1
      continue-on-error: true
      with:
        inlineScript: |
          az group lock delete --name DontDeleteMe --resource-group ${{ env.Azure_Resource_GroupName }}

    - name: Download Build Artifact-Infrastructure
      uses: actions/download-artifact@v3
      continue-on-error: false
      with:
        name: IaC
        path: ${{ github.workspace }}/IaC

      # Deploy ARM Template using Bicep DSL
    - name: Infrastructure Deploy
      id: Infra
      uses: azure/arm-deploy@v1
      continue-on-error: false
      with:
        resourceGroupName: ${{ env.Azure_Resource_GroupName }}
        template: ./IaC/main-1.bicep
        #parameters: ./IaC/main-1.params.json
        deploymentMode: Incremental
        failOnStdErr: false

    - name: Ensure Resource Group is Locked
      uses: Azure/CLI@v1
      continue-on-error: true
      with:
        inlineScript: |
          az group lock create --lock-type CanNotDelete --name DontDeleteMe --resource-group ${{ env.Azure_Resource_GroupName }} --notes 'Prevent deletion of the resource group'

    - name: DEBUG ONLY Display Output Variables
      run: |
         echo 'output_webSiteName: ${{ steps.Infra.outputs.out_webSiteName }}'
         echo 'output_keyvaultName: ${{ steps.Infra.outputs.out_keyvaultName }}'

  docker_build_pushtoacr:
    runs-on: ubuntu-latest
    needs: deploy_infrastructure

    name: Docker Build & Push to ACR
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    # - name: Setup .NET Core
    #   uses: actions/setup-dotnet@v1
    #   with:
    #     dotnet-version: ${{ env.dotnet_version }}
          
    - name: Azure authentication
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    # - name: Restore
    #   run: dotnet restore ./Application/aspnet-core-dotnet-core-net6/aspnet-core-dotnet-core-net6.csproj

    # - name: Build
    #   run: dotnet build ./Application/aspnet-core-dotnet-core-net6/aspnet-core-dotnet-core-net6.csproj --configuration ${{ env.CONFIGURATION }} --no-restore

    # - name: Publish
    #   run: dotnet publish ./Application/aspnet-core-dotnet-core-net6/aspnet-core-dotnet-core-net6.csproj --configuration ${{ env.CONFIGURATION }} --no-build --output './web'

    # - name: Upload Build Artifacts-Website
    #   uses: actions/upload-artifact@v3
    #   with:
    #     name: Web
    #     path: ${{ github.workspace }}/web

    # - name: Upload Infrastucture Files
    #   uses: actions/upload-artifact@v3
    #   with:
    #     name: IaC
    #     path: ${{ github.workspace }}/IaC/*.*

    - name: Get Azure Keyvault Values
      id: KeyVaultValue_ACRUserName
      uses: azure/CLI@v1
      with:
        #azcliversion: 2.30.0
        inlineScript: |
          result=$(az keyvault secret show --name "acrusername" --vault-name ${{ steps.Infra.outputs.out_keyvaultName }} --query "value")

    #- name: Get Azure Keyvault Values
    #  id: KeyVaultValue_ACRPassword
    #  uses: azure/CLI@v1
    #  with:
    #    #azcliversion: 2.30.0
    #    inlineScript: |
    #      result=$(az keyvault secret show --name "acrpassword" --vault-name ${{ steps.Infra.outputs.out_keyvaultName }} --query "value")

    - name: 'Get Key Vault Value'
      id: GetKVACRUserName
      uses: Azure/CLI@v1
      continue-on-error: true
      with:
        inlineScript: |
          az config set extension.use_dynamic_install=yes_without_prompt
          result=$(az keyvault secret show \
                      --name "acrusername" \
                      --vault-name "${{ needs.deploy_infrastructure.outputs.output_keyvaultName }}" \
                      --query "value" --output tsv)
          echo "::set-output name=acrusername::$result"

    - name: DEBUG ONLY Display Key Vault Secret
      run: |
          echo 'acrusername: ${{ steps.GetKVACRUserName.outputs.acrusername }}'            

    - name: 'Get Key Vault Value'
      id: GetKVACRUserPassword
      uses: Azure/CLI@v1
      continue-on-error: true
      with:
        inlineScript: |
          az config set extension.use_dynamic_install=yes_without_prompt
          result=$(az keyvault secret show \
                      --name "acrpassword" \
                      --vault-name "${{ needs.deploy_infrastructure.outputs.output_keyvaultName }}" \
                      --query "value" --output tsv)
          echo "::set-output name=acruserpassword::$result"

    - name: DEBUG ONLY Display Key Vault Secret
      run: |
          echo 'acruserpassword: ${{ steps.GetKVACRUserPassword.outputs.acruserpassword }}'    

    #- name: Docker Build & Push to ACR
    #  run: |
    #    docker login ${{ steps.Infra.outputs.output_containerregistryName }}.azurecr.io --username ${{ steps.GetKVACRUserName.outputs.acrusername }} --password ${{ steps.GetKVACRUserPassword.outputs.acruserpassword }}
    #    docker build "$GITHUB_WORKSPACE/${{env.DOCKERFILEPATH}}" -f  "${{env.DOCKERFILEPATH}}/Dockerfile" -t ${{ steps.Infra.outputs.output_containerregistryName }}.azurecr.io/${{ env.IMAGENAME }}:${{ github.sha }}

    # Create Azure container registry
    #- uses: azure/arm-deploy@v1
    #  id: createAcr
    ##  with:
    #    subscriptionId: ${{ env.SUBSCRIPTIONID }}
    #    resourceGroupName: ${{ env.RESOURCEGROUPNAME }}
    #    template: ./ArmTemplates/containerRegistry-template.json
    #    parameters: registryName="${{ env.REGISTRYNAME }}" registryLocation="${{ env.REGISTRYLOCATION }}" registrySku="${{ env.REGISTRYSKU }}"

    #- name: Fetch ACR credentials
    #  id: acrCredentials
    #  continue-on-error: false
    #  run: |
    #      echo "::set-output name=acr_username::`az acr credential show -n ${{ env.REGISTRYNAME }} --query username`"
    #      echo "::set-output name=acr_password::`az acr credential show -n ${{ env.REGISTRYNAME }} --query passwords[0].value`"
    #      echo "::add-mask::`az acr credential show -n ${{ env.REGISTRYNAME }} --query passwords[0].value`"

    #- name: ACR authentication
    #  uses: azure/docker-login@v1
    #  with:
    #    login-server: ${{ env.REGISTRYNAME }}.azurecr.io
    #    username: ${{ steps.acrCredentials.outputs.acr_username }}
    #    password: ${{ steps.acrCredentials.outputs.acr_password }}

    #- name: Docker Build & Push to ACR
    #  run: |
    #    docker login ${{ env.REGISTRYNAME }}.azurecr.io --username ${{ steps.acrCredentials.outputs.acr_username }} --password ${{ steps.acrCredentials.outputs.acr_password }}
    #    docker build "$GITHUB_WORKSPACE/${{env.DOCKERFILEPATH}}" -f  "${{env.DOCKERFILEPATH}}/Dockerfile" -t ${{ env.REGISTRYNAME }}.azurecr.io/${{ env.IMAGENAME }}:${{ github.sha }}
    #    #docker tag ${{ env.IMAGENAME }}:${{ github.sha }} ${{ env.IMAGENAME }}:latest
    #    docker push ${{ env.REGISTRYNAME }}.azurecr.io/${{ env.IMAGENAME }}:${{ github.sha }}
    
  deploy_application_to_webapp:
    name: Deploy App to Web App
    needs: docker_build_pushtoacr
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Azure authentication
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    #- uses: azure/arm-deploy@v1
    #  id: deploy
    #  with:
    #    subscriptionId: ${{ env.SUBSCRIPTIONID }}
    #    resourceGroupName: ${{ env.RESOURCEGROUPNAME }}
    #    template: ./ArmTemplates/container-webapp-template.json
    #    parameters: webAppName="${{ env.APPNAME }}" hostingPlanName="${{ env.HOSTINGPLAN }}" sku="${{ env.SKU }}" appInsightsLocation="${{ env.APPINSIGHTSLOCATION }}" registryName="${{ env.REGISTRYNAME }}" imageName="${{ env.IMAGENAME }}" registryLocation="${{ env.REGISTRYLOCATION }}" registrySku="${{ env.REGISTRYSKU }}"

    # - name: 'Deploy to Azure Web App for Container'
    #   uses: azure/webapps-deploy@v2
    #   with: 
    #     app-name: ${{ env.APPNAME }} 
    #     images: ${{ env.REGISTRYNAME }}.azurecr.io/${{ env.IMAGENAME }}:${{ github.sha }}
        
  deploy_application_to_containerapp:
    name: Deploy App to Container App
    needs: docker_build_pushtoacr
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Azure authentication
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    #- name: Get ACR credentials
    #  id: getACRCred
    #  run: |
    #       echo "::set-output name=acr_username::`az acr credential show -n ${{ env.REGISTRYNAME }} --query username | xargs`"
    #       echo "::set-output name=acr_password::`az acr credential show -n ${{ env.REGISTRYNAME }} --query passwords[0].value | xargs`"
    #       echo "::add-mask::`az acr credential show -n ${{ env.REGISTRYNAME }} --query passwords[0].value | xargs`" 

    # - name: Deploy Azure Container App Review Revisions
    #   uses: Azure/aca-review-apps@v0.2.1
    #   with:
    #     # Name of the Resource Group in which the Container App will be created
    #     resource-group: ${{ env.RESOURCEGROUPNAME }}
    #     # Name of the Container App
    #     name: 'azurecontainerapp-rpagels'
    #     # Name of Container Image. If the `mode` input is `deactivate-revision`, this input is ignored.
    #     # image: ${{ env.REGISTRYNAME }}.azurecr.io/${{ env.IMAGENAME }}:${{ github.sha }}
    #     image: ${{ env.REGISTRYNAME }}.azurecr.io/${{ env.IMAGENAME }}:latest
    #     # Suffixes for New Revision or Target Revision of deactivation. If the `mode` input is `deactivate-revision`, this input needs to be set.
    #     revision-name-suffix: 'staging'
    #     # Enable Deactivation-Revision Mode of this action. `true` or `false`. Default value is `false`
    #     #deactivate-revision-mode: # optional
    

  # FunctionalTests:
  #   name: Functional tests
  #   runs-on: windows-latest
  #   needs: [deploy_application_to_webapp, deploy_application_to_containerapp]
  #   steps:
  #   - uses: actions/checkout@master

  #   - name: Setup .NET Core
  #     uses: actions/setup-dotnet@v1
  #     with:
  #       dotnet-version: ${{ env.DOTNET_VERSION }}

  #   - name: Update web app url in Run Settings
  #     shell: powershell
  #     run: |
  #         cd Application\aspnet-core-dotnet-core.FunctionalTests
  #         [xml]$runSetting = Get-Content functionalTests.runsettings
  #         $runSetting.RunSettings.TestRunParameters.ChildNodes.Item(0).value = 'https://${{ env.APPNAME }}.azurewebsites.net/'
  #         $runSetting.Save("$(pwd)/functionalTests.runsettings")

  #   - name: Run tests
  #     continue-on-error: false
  #     run: |
  #         cd Application\aspnet-core-dotnet-core.FunctionalTests
  #         dotnet test aspnet-core-dotnet-core.FunctionalTests.csproj -s functionalTests.runsettings
