name: Trigger auto deployment for demo-container-app-rpagels

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ master ]
    paths:
    - '**'
    - '.github/workflows/demo-container-app-rpagels-AutoDeployTrigger-13099f22-2fd3-42de-a1f5-f4571f3ec4e8.yml'

  # Allow mannually trigger 
  workflow_dispatch:      

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to container registry
        uses: docker/login-action@v1
        with:
          registry: azurewebappforcontainersacr.azurecr.io
          username: ${{ secrets.DEMOCONTAINERAPPRPAGELS_REGISTRY_USERNAME }}
          password: ${{ secrets.DEMOCONTAINERAPPRPAGELS_REGISTRY_PASSWORD }}

      - name: Build and push container image to registry
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: azurewebappforcontainersacr.azurecr.io/azurewebappforcontainersedd3:${{ github.sha }}
          file: ./Dockerfile
          context: ./


  deploy:
    runs-on: ubuntu-latest
    needs: build
    
    steps:
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.DEMOCONTAINERAPPRPAGELS_AZURE_CREDENTIALS }}


      - name: Deploy to containerapp
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az config set extension.use_dynamic_install=yes_without_prompt
            az containerapp registry set -n demo-container-app-rpagels -g rg-AzureWebAppforContainers --server azurewebappforcontainersacr.azurecr.io --username  ${{ secrets.DEMOCONTAINERAPPRPAGELS_REGISTRY_USERNAME }} --password ${{ secrets.DEMOCONTAINERAPPRPAGELS_REGISTRY_PASSWORD }}
            az containerapp update -n demo-container-app-rpagels -g rg-AzureWebAppforContainers --image azurewebappforcontainersacr.azurecr.io/azurewebappforcontainersedd3:${{ github.sha }}
